import type { AttributeEnum } from "../common/AttributeType.ts";
import type { UNITS } from "../measurement_units/data.ts";

export type MunitionCategory = {
  name: string; // Наприклад, "автомати", "гранатомети", "гранати", "БПЛА" тощо
  is_transport: boolean; // Чи є ця категорія транспортом (наприклад, БПЛА)
  type_names: string[]; // Типи в цій категорії (наприклад, для "автомати" це можуть бути "АК-74", "М4", "FAMAS" тощо)
  attributes: MunitionAttribute[]; // Атрибути, специфічні для цієї категорії (наприклад, "калібр" чи "макс. дальність польоту")
};

type MunitionAttribute = {
  name: string; // Назва атрибута (наприклад, "калібр", "макс. дальність польоту")
  type: AttributeEnum; // Тип даних атрибута;
  is_enum: boolean; // Чи є цей атрибут таким, що має обмежений набір значень (ENUM)
  is_required: boolean; // Чи є цей атрибут обов'язковим для заповнення
  unit?: (typeof UNITS)[number]["abbreviation"]; // Одиниця виміру, якщо застосовно (має бути одним із значень масиву units, наприклад, "мм", "км", "кг" тощо)
  description?: string; // Опис атрибута для кращого розуміння його призначення
  enum_values?: string[]; // Якщо тип ENUM, то можливі значення
};

export const categories: MunitionCategory[] = [
  {
    name: "Основні бойові танки (ОБТ)",
    is_transport: true,
    type_names: ["M1 Abrams", "Leopard 2A7", "T-84 'Оплот'", "Challenger 3"],
    attributes: [
      {
        name: "Бойова маса",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "т",
        description: "Повна вага танка в бойовому спорядженні",
      },
      {
        name: "Калібр основної гармати",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Максимальна швидкість по шосе",
        type: "FLOAT",
        is_enum: false,
        is_required: false,
        unit: "км/год",
      },
      {
        name: "Запас ходу",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "км",
      },
      {
        name: "Тип броні",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: [
          "композитна",
          "катана гомогенна",
          "з динамічним захистом",
        ],
      },
      {
        name: "Потужність двигуна",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "к.с.",
      },
    ],
  },
  {
    name: "Бойові машини піхоти (БМП)",
    is_transport: true,
    type_names: ["M2 Bradley", "Puma", "БМП-3", "CV90"],
    attributes: [
      {
        name: "Десант",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
        description: "Кількість піхотинців, що перевозяться",
      },
      {
        name: "Основне озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Наприклад, '30-мм автоматична гармата'",
      },
      {
        name: "Бойова маса",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Наявність ПТРК",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Здатність плавати",
        type: "BOOL",
        is_enum: false,
        is_required: false,
      },
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Максимальна швидкість",
        type: "FLOAT",
        is_enum: false,
        is_required: false,
        unit: "км/год",
      },
    ],
  },
  {
    name: "Бронетранспортери (БТР)",
    is_transport: true,
    type_names: ["Stryker", "БТР-4 'Буцефал'", "Patria AMV", "Boxer"],
    attributes: [
      {
        name: "Колісна формула",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["4x4", "6x6", "8x8"],
      },
      {
        name: "Десант",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Наприклад, '12.7-мм кулемет'",
      },
      {
        name: "Рівень балістичного захисту (STANAG 4569)",
        type: "STRING",
        is_enum: true,
        is_required: false,
        enum_values: ["Рівень 1", "Рівень 2", "Рівень 3", "Рівень 4"],
      },
      {
        name: "Бойова маса",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Запас ходу",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "км",
      },
    ],
  },
  {
    name: "Самохідні артилерійські установки (САУ)",
    is_transport: true,
    type_names: ["PzH 2000", "CAESAR", "2С22 'Богдана'", "M109 Paladin"],
    attributes: [
      {
        name: "Калібр",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Максимальна дальність стрільби",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Скорострільність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "постр/хв",
      },
      {
        name: "Тип шасі",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["гусеничне", "колісне"],
      },
      {
        name: "Час розгортання",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "хв",
      },
      {
        name: "Возимий боєкомплект",
        type: "INT",
        is_enum: false,
        is_required: true,
        description: "Кількість снарядів на борту",
      },
    ],
  },
  {
    name: "Реактивні системи залпового вогню (РСЗВ)",
    is_transport: true,
    type_names: ["M142 HIMARS", "M270 MLRS", "БМ-21 'Град'", "БМ-30 'Смерч'"],
    attributes: [
      {
        name: "Калібр ракет",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Кількість напрямних",
        type: "INT",
        is_enum: false,
        is_required: true,
        description: "Кількість ракет в одному залпі",
      },
      {
        name: "Максимальна дальність ураження",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Тип боєприпасів",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["некеровані реактивні снаряди", "керовані ракети"],
      },
      {
        name: "Час повного залпу",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "с",
      },
      {
        name: "Шасі",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Модель автомобільного або гусеничного шасі",
      },
    ],
  },
  {
    name: "Винищувачі",
    is_transport: true,
    type_names: [
      "F-16 Fighting Falcon",
      "F-35 Lightning II",
      "Eurofighter Typhoon",
      "Су-27",
    ],
    attributes: [
      {
        name: "Максимальна швидкість",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        description: "Виражається в числах Маха (M)",
      },
      {
        name: "Практична стеля",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Бойовий радіус",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Основне гарматне озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Кількість точок підвіски",
        type: "INT",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Покоління",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["4", "4+", "4++", "5"],
      },
      {
        name: "Тип РЛС",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["імпульсно-доплерівська", "АФАР"],
      },
    ],
  },
  {
    name: "Ударні гелікоптери",
    is_transport: true,
    type_names: [
      "AH-64 Apache",
      "Ka-52 'Алігатор'",
      "Eurocopter Tiger",
      "Мі-24",
    ],
    attributes: [
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Максимальна злітна вага",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Крейсерська швидкість",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км/год",
      },
      {
        name: "Бойовий радіус",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Гарматне озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Калібр та тип гармати",
      },
      {
        name: "Кероване ракетне озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Типи ПТРК, ракет 'повітря-повітря'",
      },
    ],
  },
  {
    name: "Безпілотні літальні апарати (БПЛА)",
    is_transport: true,
    type_names: ["Bayraktar TB2", "MQ-9 Reaper", "Лелека-100", "Shahed-136"],
    attributes: [
      {
        name: "Тип БПЛА",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: [
          "розвідувальний",
          "ударний",
          "дрон-камікадзе",
          "багатоцільовий",
        ],
      },
      {
        name: "Максимальна дальність польоту",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Тривалість польоту",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "год",
      },
      {
        name: "Корисне навантаження",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Робоча висота",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Тип двигуна",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["поршневий", "електричний", "реактивний"],
      },
    ],
  },
  {
    name: "Ескадрені міноносці (есмінці)",
    is_transport: true,
    type_names: [
      "Arleigh Burke-class",
      "Type 45 Daring-class",
      "Zumwalt-class",
    ],
    attributes: [
      {
        name: "Водотоннажність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Довжина",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Максимальна швидкість",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "вузлів",
      },
      {
        name: "Основне ракетне озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Напр., крилаті ракети Tomahawk",
      },
      {
        name: "Наявність системи Aegis",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Авіаційна група",
        type: "STRING",
        is_enum: false,
        is_required: false,
        description: "Кількість та типи гелікоптерів",
      },
    ],
  },
  {
    name: "Підводні човни",
    is_transport: true,
    type_names: ["Virginia-class", "Yasen-class", "Astute-class", "Type 212"],
    attributes: [
      {
        name: "Тип",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: [
          "багатоцільовий атомний",
          "стратегічний ракетоносець",
          "дизель-електричний",
        ],
      },
      {
        name: "Підводна водотоннажність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Робоча глибина занурення",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Автономність",
        type: "INT",
        is_enum: false,
        is_required: true,
        description: "Тривалість походу без поповнення запасів, у добах",
      },
      {
        name: "Торпедні апарати",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Кількість та калібр",
      },
      {
        name: "Ракетне озброєння",
        type: "STRING",
        is_enum: false,
        is_required: false,
        description: "Типи балістичних або крилатих ракет",
      },
    ],
  },
  {
    name: "Автомати (штурмові гвинтівки)",
    is_transport: false,
    type_names: ["АК-74", "M4A1", "FN SCAR", "Heckler & Koch G36"],
    attributes: [
      {
        name: "Калібр",
        type: "STRING",
        is_enum: false,
        is_required: true,
        unit: "мм",
        description: "Наприклад, 5.45x39 мм",
      },
      {
        name: "Ефективна дальність стрільби",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Темп стрільби",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "постр/хв",
      },
      {
        name: "Ємність магазину",
        type: "INT",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Маса без патронів",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Режими вогню",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["одиночний", "автоматичний", "чергами"],
      },
    ],
  },
  {
    name: "Кулемети",
    is_transport: false,
    type_names: ["M240", "M2 Browning", "ПКМ", "FN Minimi"],
    attributes: [
      {
        name: "Тип кулемета",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["ручний", "єдиний", "великокаліберний"],
      },
      {
        name: "Калібр",
        type: "STRING",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Бойова скорострільність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "постр/хв",
      },
      {
        name: "Прицільна дальність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Тип живлення",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["стрічка", "магазин"],
      },
      {
        name: "Маса тіла кулемета",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
    ],
  },
  {
    name: "Снайперські гвинтівки",
    is_transport: false,
    type_names: [
      "Barrett M82",
      "CheyTac M200",
      "СВД",
      "Accuracy International AW",
    ],
    attributes: [
      {
        name: "Калібр",
        type: "STRING",
        is_enum: false,
        is_required: true,
        unit: "мм",
        description: "Наприклад, .50 BMG або 7.62x54 мм R",
      },
      {
        name: "Максимальна ефективна дальність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Принцип дії",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["поздовжньо-ковзний затвор", "самозарядна"],
      },
      {
        name: "Ємність магазину",
        type: "INT",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Довжина ствола",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "мм",
      },
      {
        name: "Оптичний приціл (штатний)",
        type: "STRING",
        is_enum: false,
        is_required: false,
      },
    ],
  },
  {
    name: "Гранатомети",
    is_transport: false,
    type_names: ["РПГ-7", "M72 LAW", "AT4", "Panzerfaust 3"],
    attributes: [
      {
        name: "Тип",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: [
          "ручний протитанковий",
          "автоматичний станковий",
          "підствольний",
        ],
      },
      {
        name: "Калібр гранати",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Прицільна дальність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Бронепробивність",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "мм",
        description: "Товщина гомогенної броні, що пробивається",
      },
      {
        name: "Тип боєприпасу",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: [
          "кумулятивний",
          "тандемний",
          "термобаричний",
          "осколковий",
        ],
      },
      { name: "Одноразовий", type: "BOOL", is_enum: false, is_required: true },
    ],
  },
  {
    name: "Протитанкові ракетні комплекси (ПТРК)",
    is_transport: false,
    type_names: ["FGM-148 Javelin", "NLAW", "Стугна-П", "Корнет"],
    attributes: [
      {
        name: "Система наведення",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: [
          "лазерний промінь",
          "інфрачервона ГСН",
          "радіокомандна",
          "по дротах",
        ],
      },
      {
        name: "Принцип 'вистрілив-забув'",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Дальність ураження (макс.)",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Тип бойової частини",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["тандемна кумулятивна", "фугасна"],
      },
      {
        name: "Бронепробивність за ДЗ",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Маса комплексу в бойовому положенні",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
    ],
  },
  {
    name: "Міномети",
    is_transport: false,
    type_names: ["M224 (60мм)", "2Б11 (120мм)", "MO-120-RT-61", "2С12 'Сані'"],
    attributes: [
      {
        name: "Калібр",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Максимальна дальність стрільби",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Мінімальна дальність стрільби",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Маса в бойовому положенні",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Скорострільність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "постр/хв",
      },
      {
        name: "Тип міни",
        type: "STRING",
        is_enum: true,
        is_required: false,
        enum_values: [
          "осколково-фугасна",
          "димова",
          "освітлювальна",
          "керована",
        ],
      },
    ],
  },
  {
    name: "Причіпні гаубиці",
    is_transport: false,
    type_names: ["M777", "FH70", "Д-30", "Д-20"],
    attributes: [
      {
        name: "Калібр",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Макс. дальність стрільби (активно-реактивним снарядом)",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Маса в похідному положенні",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Обслуга",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Кут вертикального наведення",
        type: "STRING",
        is_enum: false,
        is_required: false,
        unit: "град",
        description: "Наприклад, '-3...+70'",
      },
      {
        name: "Швидкість буксирування",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "км/год",
      },
    ],
  },
  {
    name: "Зенітні установки",
    is_transport: false,
    type_names: ["ЗУ-23-2", "Oerlikon GDF", "Bofors 40 mm L/70"],
    attributes: [
      {
        name: "Тип",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["автоматична гармата", "кулеметна установка"],
      },
      {
        name: "Калібр",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Кількість стволів",
        type: "INT",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Дальність ураження повітряних цілей",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Темп стрільби (сумарний)",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "постр/хв",
      },
      {
        name: "Висота ураження",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
    ],
  },
  {
    name: "Крилаті ракети",
    is_transport: false,
    type_names: ["Tomahawk", "Storm Shadow / SCALP-EG", "Калібр", "Нептун"],
    attributes: [
      {
        name: "Тип базування",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["повітряний", "морський", "наземний"],
      },
      {
        name: "Дальність польоту",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Маса бойової частини",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Система наведення",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Напр., 'ІНС + GPS + TERCOM + DSMAC'",
      },
      {
        name: "Маршова швидкість",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        description: "Число Маха (М)",
      },
      {
        name: "Технологія Stealth",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
    ],
  },
  {
    name: "Військові вантажівки",
    is_transport: true,
    type_names: ["Oshkosh HEMTT", "КрАЗ-6322", "MAN KAT1", "КамАЗ-6350"],
    attributes: [
      {
        name: "Колісна формула",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["4x4", "6x6", "8x8", "10x10"],
      },
      {
        name: "Вантажопідйомність",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Тип двигуна",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["дизельний", "багатопаливний"],
      },
      {
        name: "Можливість бронювання кабіни",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Об'єм паливного бака",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "л",
      },
      {
        name: "Глибина броду, що долається",
        type: "FLOAT",
        is_enum: false,
        is_required: false,
        unit: "м",
      },
    ],
  },
  {
    name: "Бойові розвідувальні машини (БРМ)",
    is_transport: true,
    type_names: ["БРДМ-2", "Fennek", "Spähpanzer Luchs", "БРМ-1К"],
    attributes: [
      {
        name: "Тип шасі",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["гусеничне", "колісне"],
      },
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Основне розвідувальне обладнання",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "РЛС, тепловізор, далекомір",
      },
      { name: "Озброєння", type: "STRING", is_enum: false, is_required: true },
      {
        name: "Запас ходу",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "км",
      },
      {
        name: "Здатність плавати",
        type: "BOOL",
        is_enum: false,
        is_required: false,
      },
    ],
  },
  {
    name: "Зенітні самохідні установки (ЗСУ)",
    is_transport: true,
    type_names: ["Gepard", "2С6М 'Тунгуска'", "Shilka", "K30 Biho"],
    attributes: [
      {
        name: "Тип озброєння",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["гарматне", "ракетне", "комбіноване"],
      },
      {
        name: "Калібр гармат",
        type: "FLOAT",
        is_enum: false,
        is_required: false,
        unit: "мм",
      },
      {
        name: "Дальність виявлення цілі РЛС",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Максимальна висота ураження",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Час реакції",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "с",
      },
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
    ],
  },
  {
    name: "Інженерні машини розгородження (ІМР)",
    is_transport: true,
    type_names: ["ІМР-2", "Bionix-ІМР", "Terrier Armoured Digger"],
    attributes: [
      {
        name: "Базове шасі",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Зазвичай, танкове",
      },
      {
        name: "Основне робоче обладнання",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Бульдозер, кран, мінний трал",
      },
      {
        name: "Продуктивність (прокладання колонного шляху)",
        type: "FLOAT",
        is_enum: false,
        is_required: false,
        unit: "км/год",
      },
      {
        name: "Вантажопідйомність крана",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Зазвичай, кулемет",
      },
    ],
  },
  {
    name: "Броньовані ремонтно-евакуаційні машини (БРЕМ)",
    is_transport: true,
    type_names: ["БРЕМ-1", "M88 Recovery Vehicle", "Bergepanzer Büffel"],
    attributes: [
      {
        name: "Тягове зусилля основної лебідки",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Вантажопідйомність крана",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Максимальна маса евакуйованої техніки",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Наявність зварювального обладнання",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Базове шасі",
        type: "STRING",
        is_enum: false,
        is_required: true,
      },
    ],
  },
  {
    name: "Оперативно-тактичні ракетні комплекси (ОТРК)",
    is_transport: true,
    type_names: ["ATACMS", "Іскандер", "Точка-У", "Грім-2"],
    attributes: [
      {
        name: "Тип ракети",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["балістична", "аеробалістична", "крилата"],
      },
      {
        name: "Максимальна дальність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Кругове імовірне відхилення (КІВ)",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Тип бойової частини",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["касетна", "осколково-фугасна", "ядерна"],
      },
      {
        name: "Кількість ракет на пусковій установці",
        type: "INT",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Час підготовки до пуску",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "хв",
      },
    ],
  },
  {
    name: "Балістичні ракети",
    is_transport: false,
    type_names: ["LGM-30 Minuteman", "Trident II", "РС-28 'Сармат'"],
    attributes: [
      {
        name: "Клас",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["МБР", "БРПЧ", "середньої дальності"],
      },
      {
        name: "Тип базування",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["шахтний", "мобільний ґрунтовий", "підводний човен"],
      },
      {
        name: "Максимальна дальність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Тип головної частини",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["моноблочна", "розділювана (РГЧ ІН)"],
      },
      {
        name: "Стартова маса",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Кількість бойових блоків",
        type: "INT",
        is_enum: false,
        is_required: false,
      },
    ],
  },
  {
    name: "Бомбардувальники",
    is_transport: true,
    type_names: ["B-52 Stratofortress", "B-2 Spirit", "Ту-160", "Ту-95"],
    attributes: [
      {
        name: "Тип",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["стратегічний", "тактичний"],
      },
      {
        name: "Максимальне бойове навантаження",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Бойовий радіус",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Практична стеля",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Наявність технології Stealth",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
    ],
  },
  {
    name: "Штурмовики",
    is_transport: true,
    type_names: [
      "A-10 Thunderbolt II",
      "Су-25",
      "Embraer EMB 314 Super Tucano",
    ],
    attributes: [
      {
        name: "Основне гарматне озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Наприклад, '30-мм семиствольна GAU-8'",
      },
      {
        name: "Максимальне бойове навантаження",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Бронювання",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Наявність та тип бронювання кабіни та важливих вузлів",
      },
      {
        name: "Кількість точок підвіски",
        type: "INT",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Крейсерська швидкість",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "км/год",
      },
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
    ],
  },
  {
    name: "Військово-транспортні літаки",
    is_transport: true,
    type_names: [
      "C-130 Hercules",
      "C-5 Galaxy",
      "Ан-225 'Мрія'",
      "Airbus A400M Atlas",
    ],
    attributes: [
      {
        name: "Максимальна вантажопідйомність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Об'єм вантажної кабіни",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м³",
      },
      {
        name: "Кількість десантників, що перевозяться",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "осіб",
      },
      {
        name: "Практична дальність (з макс. навантаженням)",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Тип шасі",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["стандартне", "підвищеної прохідності"],
      },
      {
        name: "Наявність вантажної рампи",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
    ],
  },
  {
    name: "Транспортно-бойові гелікоптери",
    is_transport: true,
    type_names: ["UH-60 Black Hawk", "Мі-8/Мі-17", "NHIndustries NH90"],
    attributes: [
      {
        name: "Кількість десантників",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Вантажопідйомність у кабіні",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Вантажопідйомність на зовнішній підвісці",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Озброєння",
        type: "STRING",
        is_enum: false,
        is_required: false,
        description: "Кулемети, некеровані ракети",
      },
      {
        name: "Практична дальність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
    ],
  },
  {
    name: "Авіаносці",
    is_transport: true,
    type_names: [
      "Gerald R. Ford-class",
      "Queen Elizabeth-class",
      "Charles de Gaulle",
    ],
    attributes: [
      {
        name: "Тип силової установки",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["ядерна", "звичайна"],
      },
      {
        name: "Повна водотоннажність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Кількість літальних апаратів",
        type: "INT",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Тип злітної системи",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["катапульта (CATOBAR)", "трамплін (STOBAR/STOVL)"],
      },
      {
        name: "Довжина польотної палуби",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Екіпаж (включаючи авіакрило)",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
    ],
  },
  {
    name: "Крейсери",
    is_transport: true,
    type_names: ["Ticonderoga-class", "Проект 1144 'Орлан'"],
    attributes: [
      {
        name: "Призначення",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["ракетний", "важкий атомний ракетний"],
      },
      {
        name: "Повна водотоннажність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Основне ударне озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Типи та кількість протикорабельних/крилатих ракет",
      },
      {
        name: "Система ППО/ПРО",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Наприклад, ЗРК 'Форт'",
      },
      {
        name: "Дальність плавання",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "км",
        description: "Для неатомних - при економічній швидкості",
      },
      {
        name: "Автономність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "діб",
      },
    ],
  },
  {
    name: "Фрегати",
    is_transport: true,
    type_names: ["FREMM", "Type 26", "Адмірал Григорович-клас"],
    attributes: [
      {
        name: "Повна водотоннажність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Спеціалізація",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["ППО", "ПЧО", "багатоцільовий"],
      },
      {
        name: "Ракетне озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Кількість пускових установок та типи ракет",
      },
      {
        name: "Артилерійське озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Наявність ангару для гелікоптера",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Максимальна швидкість",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "вузлів",
      },
    ],
  },
  {
    name: "Корвети",
    is_transport: true,
    type_names: ["Sa'ar 6", "Visby-class", "Проект 20380 'Стерегущий'"],
    attributes: [
      {
        name: "Повна водотоннажність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Застосування технології Stealth",
        type: "BOOL",
        is_enum: false,
        is_required: false,
      },
      {
        name: "Протикорабельні ракети",
        type: "STRING",
        is_enum: false,
        is_required: true,
      },
      {
        name: "ЗРК ближнього радіусу дії",
        type: "STRING",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Дальність плавання",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
    ],
  },
  {
    name: "Десантні кораблі",
    is_transport: true,
    type_names: ["Mistral-class", "Wasp-class", "Juan Carlos I"],
    attributes: [
      {
        name: "Тип",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: [
          "УДК",
          "танкодесантний",
          "десантний катер на повітряній подушці",
        ],
      },
      {
        name: "Десантомісткість (особовий склад)",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Десантомісткість (техніка)",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Кількість танків або БТР",
      },
      {
        name: "Наявність докової камери",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Авіагрупа",
        type: "STRING",
        is_enum: false,
        is_required: false,
        description: "Кількість та типи гелікоптерів",
      },
      {
        name: "Повна водотоннажність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
    ],
  },
  {
    name: "Мінні тральщики",
    is_transport: true,
    type_names: [
      "Sandown-class",
      "Avenger-class",
      "Проект 12700 'Александрит'",
    ],
    attributes: [
      {
        name: "Призначення",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: [
          "морський тральщик",
          "базовий тральщик",
          "рейдовий тральщик",
        ],
      },
      {
        name: "Матеріал корпусу",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["склопластик", "дерево", "маломагнітна сталь"],
      },
      {
        name: "Тип тралів",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Контактний, неконтактний (акустичний, електромагнітний)",
      },
      {
        name: "Наявність підводних апаратів",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Повна водотоннажність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Екіпаж",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
    ],
  },
  {
    name: "Ракетні катери",
    is_transport: true,
    type_names: ["Skjold-class", "Проект 1241 'Молнія'", "Houbei type 22"],
    attributes: [
      {
        name: "Повна водотоннажність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Максимальна швидкість",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "вузлів",
      },
      {
        name: "Кількість пускових установок ПКР",
        type: "INT",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Тип протикорабельних ракет",
        type: "STRING",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Артилерійське озброєння",
        type: "STRING",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Тип корпусу",
        type: "STRING",
        is_enum: true,
        is_required: false,
        enum_values: ["монокорпусний", "катамаран", "на повітряній подушці"],
      },
    ],
  },
  {
    name: "Пістолети",
    is_transport: false,
    type_names: [
      "Glock 17",
      "Beretta 92",
      "SIG Sauer P320",
      "Пістолет Макарова",
    ],
    attributes: [
      {
        name: "Калібр",
        type: "STRING",
        is_enum: false,
        is_required: true,
        unit: "мм",
        description: "Наприклад, 9x19 мм Parabellum",
      },
      {
        name: "Принцип дії",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["короткий хід ствола", "вільний затвор"],
      },
      {
        name: "Ємність магазину",
        type: "INT",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Маса без патронів",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "г",
      },
      {
        name: "Матеріал рамки",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["полімер", "сталь", "алюмінієвий сплав"],
      },
      {
        name: "Тип УСМ",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: [
          "ударниковий",
          "курковий подвійної дії",
          "курковий одинарної дії",
        ],
      },
    ],
  },
  {
    name: "Паливозаправники",
    is_transport: true,
    type_names: ["АЦ-10-260", "KC-135 Stratotanker", "Oshkosh PLS M1075"],
    attributes: [
      {
        name: "Тип",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["автомобільний", "літак-заправник"],
      },
      {
        name: "Об'єм цистерни / палива, що передається",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "л",
      },
      {
        name: "Базове шасі / літак",
        type: "STRING",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Продуктивність насоса",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "л/хв",
      },
      {
        name: "Кількість точок заправки",
        type: "INT",
        is_enum: false,
        is_required: false,
      },
      {
        name: "Типи палива, що транспортуються",
        type: "STRING",
        is_enum: false,
        is_required: true,
      },
    ],
  },
  {
    name: "Броньовані медичні машини",
    is_transport: true,
    type_names: ["M1133 MEV", "БММ-4С", "Pandur 6x6 Ambulance"],
    attributes: [
      {
        name: "Базове шасі",
        type: "STRING",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Кількість лежачих поранених",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Кількість сидячих поранених",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
      {
        name: "Наявність медичного обладнання",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Наприклад, апарат ШВЛ, дефібрилятор",
      },
      {
        name: "Рівень балістичного захисту",
        type: "STRING",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Екіпаж (включаючи медиків)",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "осіб",
      },
    ],
  },
  {
    name: "Машини радіоелектронної боротьби (РЕБ)",
    is_transport: true,
    type_names: [
      "'Буковель-AD'",
      "EA-18G Growler",
      "'Красуха'",
      "Р-330Ж 'Житель'",
    ],
    attributes: [
      {
        name: "Призначення",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: [
          "придушення зв'язку",
          "протидія РЛС",
          "захист від БПЛА",
          "радіотехнічна розвідка",
        ],
      },
      {
        name: "Діапазон робочих частот",
        type: "STRING",
        is_enum: false,
        is_required: true,
        unit: "МГц",
      },
      {
        name: "Ефективний радіус дії",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Тип носія",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["автомобільний", "авіаційний", "стаціонарний", "носимий"],
      },
      {
        name: "Вихідна потужність передавача",
        type: "FLOAT",
        is_enum: false,
        is_required: false,
        unit: "кВт",
      },
      {
        name: "Час розгортання",
        type: "INT",
        is_enum: false,
        is_required: false,
        unit: "хв",
      },
    ],
  },
  {
    name: "Понтонно-мостові парки",
    is_transport: true,
    type_names: ["ПМП-М", "M3 Amphibious Rig", "Improved Ribbon Bridge"],
    attributes: [
      {
        name: "Вантажопідйомність мосту",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "т",
      },
      {
        name: "Максимальна довжина мосту (з одного комплекту)",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Час наведення мосту",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "хв",
      },
      {
        name: "Ширина проїзної частини",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Можливість використання як пором",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Транспортна база",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "Наприклад, вантажівки КрАЗ",
      },
    ],
  },
  {
    name: "Шляхопрокладачі",
    is_transport: true,
    type_names: ["БАТ-2", "M9 ACE", "CET (Combat Engineer Tractor)"],
    attributes: [
      {
        name: "Базове шасі",
        type: "STRING",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Продуктивність (прокладання колонного шляху)",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км/год",
      },
      {
        name: "Продуктивність (землерийні роботи)",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "м³/год",
      },
      {
        name: "Вантажопідйомність крана",
        type: "FLOAT",
        is_enum: false,
        is_required: false,
        unit: "т",
      },
      {
        name: "Тип відвалу",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["прямий", "двохвідвальний", "V-подібний"],
      },
      {
        name: "Здатність плавати",
        type: "BOOL",
        is_enum: false,
        is_required: false,
      },
    ],
  },
  {
    name: "Командно-штабні машини (КШМ)",
    is_transport: true,
    type_names: ["Р-149БМР 'Кушетка-Б'", "M577", "Boxer Command Post"],
    attributes: [
      {
        name: "Базове шасі",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "БТР, БМП або вантажівка",
      },
      {
        name: "Кількість автоматизованих робочих місць",
        type: "INT",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Типи зв'язку",
        type: "STRING",
        is_enum: false,
        is_required: true,
        description: "КХ, УКХ, супутниковий",
      },
      {
        name: "Наявність автономного джерела живлення",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Рівень захисту",
        type: "STRING",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Час розгортання",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "хв",
      },
    ],
  },
  {
    name: "Переносні зенітно-ракетні комплекси (ПЗРК)",
    is_transport: false,
    type_names: ["FIM-92 Stinger", "Starstreak", "'Ігла'", "Grom"],
    attributes: [
      {
        name: "Тип головки самонаведення",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["інфрачервона", "ультрафіолетова", "лазерна"],
      },
      {
        name: "Дальність ураження цілі",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Висота ураження цілі",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Максимальна швидкість цілі",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м/с",
      },
      {
        name: "Маса в бойовому положенні",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Можливість роботи вночі",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
    ],
  },
  {
    name: "Вогнемети",
    is_transport: false,
    type_names: ["РПО 'Шмель'", "M202 FLASH", "LPO-50"],
    attributes: [
      {
        name: "Тип",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["реактивний піхотний", "струменевий"],
      },
      {
        name: "Тип боєприпасу",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["термобаричний", "запалювальний", "димовий"],
      },
      {
        name: "Прицільна дальність",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Маса",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Калібр",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      { name: "Одноразовий", type: "BOOL", is_enum: false, is_required: true },
    ],
  },
  {
    name: "Протитанкові міни",
    is_transport: false,
    type_names: ["ТМ-62М", "M15", "AT2"],
    attributes: [
      {
        name: "Тип детонатора",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["натискний", "магнітний", "сейсмічний", "інфрачервоний"],
      },
      {
        name: "Маса вибухової речовини",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Матеріал корпусу",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["метал", "пластик", "дерево"],
      },
      {
        name: "Тип ураження",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["протигусенична", "протиднищева", "бортова"],
      },
      {
        name: "Можливість знешкодження",
        type: "BOOL",
        is_enum: false,
        is_required: true,
      },
      {
        name: "Загальна маса",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
    ],
  },
  {
    name: "Ручні гранати",
    is_transport: false,
    type_names: ["Ф-1", "РГД-5", "M67", "DM51"],
    attributes: [
      {
        name: "Тип",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: [
          "оборонна",
          "наступальна",
          "протитанкова",
          "димова",
          "світлошумова",
        ],
      },
      {
        name: "Радіус суцільного ураження",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
      {
        name: "Час уповільнення запалу",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "с",
      },
      {
        name: "Маса",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "г",
      },
      {
        name: "Маса вибухової речовини",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "г",
      },
      {
        name: "Матеріал корпусу",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["чавун", "сталь", "пластик"],
      },
    ],
  },
  {
    name: "Торпеди",
    is_transport: false,
    type_names: ["Mark 48", "'Фізик'", "Spearfish"],
    attributes: [
      {
        name: "Калібр",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "мм",
      },
      {
        name: "Система наведення",
        type: "STRING",
        is_enum: true,
        is_required: true,
        enum_values: ["активна/пасивна акустична", "телекерування по дроту"],
      },
      {
        name: "Дальність ходу",
        type: "FLOAT",
        is_enum: false,
        is_required: true,
        unit: "км",
      },
      {
        name: "Максимальна швидкість",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "вузлів",
      },
      {
        name: "Маса бойової частини",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "кг",
      },
      {
        name: "Глибина ходу",
        type: "INT",
        is_enum: false,
        is_required: true,
        unit: "м",
      },
    ],
  },
];
